### ISSUE TITLE
Running out of memory on some systems

### ISSUE THREAD

**Issue by winneratwin** [Earthcomputer/EnchantmentCracker#20]
![image](https://user-images.githubusercontent.com/32520794/39796393-822ba6d6-5356-11e8-9d09-ce49238bc770.png)
[enchcracker.log](https://github.com/Earthcomputer/EnchantmentCracker/files/1986449/enchcracker.log)
constant crash when trying to find out my seed at 3325000000 out of 4294967296 seeds checked

**Comment by Earthcomputer** [comment]
I thought I solved the memory issues in the last update I did yesterday, apparently not.
It looks like I need to put more thought into how the cracker can use RAM more efficiently in exchange for a little more time taken to crack the XP seed.
While I do that, a temporary solution that you could use is allocate more RAM to the cracker. Inside `enchcracker.bat` there is an `-Xmx2g` option. Increase it to something larger. `-Xmx4g` should be plenty.

**Comment by winneratwin** [comment]
just fyi it was only that enchantment level book combination that made me crash

**Comment by Earthcomputer** [comment]
I believe I have implemented a fix, but since it's such a major change to the internals, I need to test it more thoroughly before releasing it.

**Comment by Earthcomputer** [comment]
Sorry about the delay here, been working hard on the world rng cracking and haven't had time to fix this yet (my previous fix was a little broken). I'll get back to it as soon as possible!

**Comment by fibular** [comment]
Cheers, although i shouldn't be having any problems with ram; currently have 16gigs running at this moment in time.

**Comment by fibular** [comment]
Just allocated more RAM, still get the same problem.

**Comment by Earthcomputer** [comment]
If you really have 16GB of RAM then it shouldn't be a problem. Try closing some other programs to free up some memory for the cracker.

**Comment by fibular** [comment]
I do, doing a full clearance of java on my computer to see if it could possibly help at all. Will get back to you if i have found a fix.

**Comment by fibular** [comment]
Fixed it, did a full wipe of java, must have had some old versions still attempting to be used within my pc, thanks for the help mate!

**Comment by pogosogos** [comment]
This issue is still present no matter what I have tried. When I change the -Xmx2g to -Xmx4g it just comes up with another error message: Error: could not create the java virtual machine.

![image](https://user-images.githubusercontent.com/44418263/47397134-c1346b80-d725-11e8-90d6-9876b20a3f3a.png)

**Comment by Earthcomputer** [comment]
The problem is, the enchantment cracker simply requires this amount of memory in order to function. I have tried some potential workarounds but they all make it significantly slower.

**Comment by Earthcomputer** [comment]
Should be fixed in version 1.4, hopefully

**Comment by JammieDodger0908** [comment]
I spent like 20 mins trying to get the right path for JAVA_HOME and now when i try to use it i get this message:

Error: Could not find or load main class enchcracker.EnchCrackerWindow
Caused by: java.lang.ClassNotFoundException: enchcracker.EnchCrackerWindow
Failed to launch enchcracker!
